In [10]:
pip install mlxtend

     ---------------------------------------- 1.3/1.3 MB 9.5 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.2.2 -> 22.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [22]:
from datetime import datetime
print('-------------------Rule based method(Demonstrating OneR on a discretized Iris dataset)-----------------')
print('Name: Farhana Khatoon Abdul Rashid')
print('Roll No.21')
print('College name: Vivek College of Commerce')
print('M.sc(I.T)[Sem 3]')
now = datetime.now()
# dd/mm/YY H:M:S
dt_string = now.strftime("%d/%m/%Y %H:%M:%S")
print("Date and Time =", dt_string)	
import numpy as np 
import pandas as pd
from sklearn import metrics
from mlxtend.data import iris_data
X, y = iris_data()
print("\n X:- \n", X[:15])
import numpy as np
def get_feature_quartiles(X):
    X_discretized = X.copy()
    for col in range(X.shape[1]):
        for q, class_label in zip([1.0, 0.75, 0.5, 0.25], [3, 2, 1, 0]):
            threshold = np.quantile(X[:, col], q=q)
            X_discretized[X[:, col] <= threshold, col] = class_label
    return X_discretized.astype(np.int)

Xd=get_feature_quartiles(X)
print(" \n After each feature is divided into 4 quartiles:- \n", xd[:10])
#Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
Xd_train, Xd_test, y_train, y_test = train_test_split(Xd, y, random_state=0, stratify=y)
#Now train a OneRClassifier model on the training set using the fit method
from mlxtend.classifier import OneRClassifier
oner = OneRClassifier()_
oner.fit(Xd_train, y_train)
#The column index of the selected feature is accessible via the feature_idx_ attribute after model fitting
print("\n Index of feature:-", oner.feature_idx_)
print("\n Lists of total error for the selected feature(the feature listed under feature_idx_):- ", oner.prediction_dict_)
#Making prediction
#For training
y_pred = oner.predict(Xd_train)
train_acc = np.mean(y_pred == y_train)  
print(f'Training accuracy:- {train_acc*100:.2f}%')
#For testing
from sklearn import metrics
y_pred = oner.predict(Xd_test)
test_acc = np.mean(y_pred == y_test)  
print(f'Test accuracy:- {test_acc*100:.2f}%')

-------------------Rule based method(Demonstrating OneR on a discretized Iris dataset)-----------------
Name: Farhana Khatoon Abdul Rashid
Roll No.21
College name: Vivek College of Commerce
M.sc(I.T)[Sem 3]
Date and Time = 24/11/2022 09:25:34

 X:- 
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]]
 
 After each feature is divided into 4 quartiles:- 
 [[0 3 0 0]
 [0 1 0 0]
 [0 2 0 0]
 [0 2 0 0]
 [0 3 0 0]
 [1 3 1 1]
 [0 3 0 0]
 [0 3 0 0]
 [0 1 0 0]
 [0 2 0 0]]

 Index of feature:- 2

 Lists of total error for the selected feature(the feature listed under feature_idx_):-  {'total error': 16, 'rules (value: class)': {0: 0, 1: 1, 2: 1, 3: 2}}
Training accuracy:- 85.71%
Test accuracy:- 84.21%


C:\Users\Mscit6\AppData\Local\Temp\ipykernel_3744\2348894946.py:24: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  return X_discretized.astype(np.int)


In [19]:
from datetime import datetime
print('---------------Rule based method(Demonstrating Association Rule)--------------')
print('Name: Farhana Khatoon Abdul Rashid')
print('Roll No.21')
print('College name: Vivek College of Commerce')
print('M.sc(I.T)[Sem 3]')
now = datetime.now()
# dd/mm/YY H:M:S
dt_string = now.strftime("%d/%m/%Y %H:%M:%S")
print("Date and Time =", dt_string)	
import pandas as pd
#Creating a list with the required data
dataset = [
    ["Milk", "Eggs", "Bread"],
    ["Milk", "Eggs"],
    ["Milk", "Bread"],
    ["Eggs", "Apple"],
]
print("Dataset:-\n ",dataset)
#Convert list to dataframe with boolean values
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder

te = TransactionEncoder()
te_array = te.fit(dataset).transform(dataset)
df = pd.DataFrame(te_array, columns=te.columns_)
print("Dataframe:- \n", df)
print("\n")
#Find frequently occurring itemsets using Apriori Algorithm
from mlxtend.frequent_patterns import apriori
frequent_itemsets_ap = apriori(df, min_support=0.01, use_colnames=True)
print("=====Frequently occurring itemsets====== \n", frequent_itemsets_ap)
#Find frequently occurring itemsets using F-P Growth
from mlxtend.frequent_patterns import fpgrowth
frequent_itemsets_fp=fpgrowth(df, min_support=0.01, use_colnames=True)
print("\n =====Frequently occurring itemsets using F-P Growth===== \n", frequent_itemsets_fp)
#Mine the Association Rules
from mlxtend.frequent_patterns import association_rules
rules_ap = association_rules(frequent_itemsets_ap, metric="confidence", min_threshold=0.8)
rules_fp = association_rules(frequent_itemsets_fp, metric="confidence", min_threshold=0.8)
print("\n =====Both sets of rules===== \n", rules_ap)

---------------Rule based method(Demonstrating Association Rule)--------------
Name: Farhana Khatoon Abdul Rashid
Roll No.21
College name: Vivek College of Commerce
M.sc(I.T)[Sem 3]
Date and Time = 28/11/2022 10:52:27
Dataset:-
  [['Milk', 'Eggs', 'Bread'], ['Milk', 'Eggs'], ['Milk', 'Bread'], ['Eggs', 'Apple']]
Dataframe:- 
    Apple  Bread   Eggs   Milk
0  False   True   True   True
1  False  False   True   True
2  False   True  False   True
3   True  False   True  False


=====Frequently occurring itemsets====== 
    support             itemsets
0     0.25              (Apple)
1     0.50              (Bread)
2     0.75               (Eggs)
3     0.75               (Milk)
4     0.25        (Eggs, Apple)
5     0.25        (Bread, Eggs)
6     0.50        (Bread, Milk)
7     0.50         (Eggs, Milk)
8     0.25  (Bread, Eggs, Milk)

 =====Frequently occurring itemsets using F-P Growth===== 
    support             itemsets
0     0.75               (Milk)
1     0.75               (Eggs)
